services:
  location_consumer:
    build: .
    environment:
      - DB_HOST=localhost
      - DB_PORT=5433
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
      - DB_NAME=postgres
      - KAFKA_URL=localhost:9092
    network_mode: "host"

