apiVersion: v1
kind: Service
metadata:
  labels:
    service: location-consumer
  name: location-consumer
spec:
  ports:
  - name: "5000"
    port: 5000
    targetPort: 5000
  selector:
    service: location-consumer
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: location-consumer
  name: location-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      service: location-consumer
  template:
    metadata:
      labels:
        service: location-consumer
    spec:
      containers:
      - image: tts2k/location_consumer:latest
        name: location-consumer
        imagePullPolicy: Always
        env:
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_PORT
        - name: KAFKA_URL
          valueFrom:
            configMapKeyRef:
              name: kafka-env
              key: KAFKA_URL
      restartPolicy: Always
